INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6401','Perez','Perez','Juan','1980-01-01');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6402','Bolivar','Palacios','Simon','1985-02-02');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6403','Fernandez','Taboada','Maria','1990-03-03');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6404','Revilla','Lenoci','Angel David','1995-04-04');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6405','Domingo','Murillo','Pedro','2000-05-05');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6406', 'García', 'López', 'Ana María', '1982-06-15');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6407', 'Martínez', 'Sánchez', 'Carlos', '1975-07-22');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6408', 'Rodríguez', 'Gómez', 'Laura', '1988-08-30');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6409', 'López', 'Fernández', 'Javier', '1979-09-18');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6410', 'González', 'Martín', 'Lucía', '1991-10-05');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6411', 'Sánchez', 'Pérez', 'Roberto', '1984-11-12');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6412', 'Díaz', 'Ruiz', 'Elena', '1987-12-28');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6413', 'Moreno', 'Jiménez', 'Francisco', '1980-01-15');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6414', 'Ruiz', 'Hernández', 'Cristina', '1976-02-09');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6415', 'Hernández', 'Díaz', 'Miguel', '1989-03-21');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6416', 'Vargas', 'Mendoza', 'Ricardo', '1983-04-12');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6417', 'Castro', 'Rojas', 'Elena', '1977-08-19');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6418', 'Acosta', 'Guzmá', 'Federico', '1982-03-07');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6419', 'Morales', 'Soto', 'Gabriela', '1990-12-11');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6420', 'Herrera', 'Cabrera', 'Andrés', '1985-06-25');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6421', 'Paredes', 'Lozano', 'Claudia', '1979-09-30');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6422', 'Salinas', 'Vega', 'Oscar', '1987-11-03');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6423', 'Rivas', 'Bello', 'Patricia', '1992-07-14');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6424', 'Núñez', 'Cervantes', 'Diego', '1980-05-20');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6425', 'Fuentes', 'Pacheco', 'Mónica', '1986-08-08');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6426', 'Beltrá', 'Gutiérrez', 'Javier', '1978-10-17');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6427', 'Cordero', 'Soler', 'Isabel', '1991-02-28');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6428', 'Miranda', 'Alvarado', 'Sergio', '1984-04-04');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6429', 'Ramos', 'Quispe', 'Verónica', '1989-01-09');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6430', 'Espinoza', 'Cruz', 'Alejandro', '1976-12-20');