INSERT INTO servicios.medico(dni,apPaterno,apMaterno,nombres,fechaNacimiento) VALUES ('6401','Perez','Perez','Juan','1980-01-01');
INSERT INTO servicios.medico(dni,apPaterno,apMaterno,nombres,fechaNacimiento) VALUES ('6402','Bolivar','Palacios','Simon','1985-02-02');
INSERT INTO servicios.medico(dni,apPaterno,apMaterno,nombres,fechaNacimiento) VALUES ('6403','Fernandez','Taboada','Maria','1990-03-03');
INSERT INTO servicios.medico(dni,apPaterno,apMaterno,nombres,fechaNacimiento) VALUES ('6404','Revilla','Lenoci','Angel David','1995-04-04');
INSERT INTO servicios.medico(dni,apPaterno,apMaterno,nombres,fechaNacimiento) VALUES ('6405','Domingo','Murillo','Pedro','2000-05-05');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6406', 'García', 'López', 'Ana María', '1982-06-15');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6407', 'Martínez', 'Sánchez', 'Carlos', '1975-07-22');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6408', 'Rodríguez', 'Gómez', 'Laura', '1988-08-30');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6409', 'López', 'Fernández', 'Javier', '1979-09-18');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6410', 'González', 'Martín', 'Lucía', '1991-10-05');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6411', 'Sánchez', 'Pérez', 'Roberto', '1984-11-12');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6412', 'Díaz', 'Ruiz', 'Elena', '1987-12-28');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6413', 'Moreno', 'Jiménez', 'Francisco', '1980-01-15');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6414', 'Ruiz', 'Hernández', 'Cristina', '1976-02-09');
INSERT INTO servicios.medico (dni, apPaterno, apMaterno, nombres, fechaNacimiento) VALUES ('6415', 'Hernández', 'Díaz', 'Miguel', '1989-03-21');