CREATE TABLE [servicios].[servicio]
(
	[IdServicio] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, --PK AUTOINCREMENTAL
	[nombre] NVARCHAR(200) NOT NULL,
	[acronimo] NVARCHAR(50),
	[comentario] NVARCHAR(1000),
	CONSTRAINT [Pk_servicio] PRIMARY KEY CLUSTERED ([IdServicio] ASC)
	 WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, 
          ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
    ON [PRIMARY]
) ON [PRIMARY];
GO
