CREATE TABLE [dbo].[DimServicio]
(
	[idServicioSK] INT IDENTITY(1,1) NOT NULL, --PK AUTOINCREMENTAL
	[idServicio] INT NOT NULL,
	[nombre] NVARCHAR(200) NOT NULL,
	[acronimo] NVARCHAR(50),
	[comentario] NVARCHAR(1000),
	CONSTRAINT [PK_DimServicio] PRIMARY KEY CLUSTERED ([idServicioSK] ASC)
	 WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, 
          ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
    ON [PRIMARY]
) ON [PRIMARY]
GO